name: Web page
on:
    push:
        branches: ["main"]
    workflow_dispatch:
permissions:
    contents: read
    pages: write
    id-token: write
concurrency:
    group: pages
    cancel-in-progress: false
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "hello World"
           - name: Clone Repo
             uses: actions/checkout@v3
            - name: setup git hub pages
              uses: action/configure-pagesv3
            - name: upload artifact
              use: actions/upload-pages-artifact@v2
              with:
                path: "./dist/"

 #             run : git clone git@github.com:sabinlucea/demo-github-action.git

