name: Web page
on:
    push:
        branches: ["main"]
    workflow_dispatch:
permissions:
    contents: read
    pages: write
    id-token: write
concurrency:
    group: pages
    cancel-in-progress: false
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "hello World"
